-- AlterTable
ALTER TABLE "User" ADD COLUMN     "accuracy" DOUBLE PRECISION NOT NULL DEFAULT 0.6,
ADD COLUMN     "passedMissionCnt" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalMissionCnt" INTEGER NOT NULL DEFAULT 0;
